import type { Car } from '../../types';

const getCars = (): Car[] => {
  return [
    {
      id: 1,
      make: 'Ford',
      model: 'Mustang',
      year: 2020,
      price: 450000,
      imageUrl: '/images/mustang.jpg',
      engine: '5.0L 8-Cylinder DOHC 32V',
      transmission: 'Automatic',
      fuelType: 'Gasoline',
      color: 'Red',
      mileage: 3000000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
      ],
      technologies: [
        'Sync 3 infotainment system',
        'Ford Co-Pilot360 driver assist technology',
        'EcoBoost engine technology',
      ],
    },
    {
      id: 2,
      make: 'Tesla',
      model: 'Model 3',
      year: 2021,
      price: 4000000,
      imageUrl: '/images/model3.jpg',
      engine: 'Electric Motor',
      transmission: 'Automatic',
      fuelType: 'Electric',
      color: 'Black',
      mileage: 40000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
      ],
      technologies: [
        'Autopilot advanced safety and convenience feature',
        'Supercharger network for fast charging',
        'Full self-driving capability',
      ],
    },
    {
      id: 3,
      make: 'Toyota',
      model: 'Corolla',
      year: 2019,
      price: 200000,
      imageUrl: '/images/corolla.jpg',
      engine: '1.8L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Silver',
      mileage: 10000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
      ],
      technologies: [
        'Toyota Safety Sense driver assist technology',
        'Entune infotainment system',
        'Hybrid Synergy Drive system',
      ],
    },
    {
      id: 4,
      make: 'Honda',
      model: 'Civic',
      year: 2018,
      price: 180000,
      imageUrl: '/images/civic.jpg',
      engine: '2.0L 4-Cylinder DOHC 16V',
      transmission: 'Manual',
      fuelType: 'Gasoline',
      color: 'White',
      mileage: 20000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
      ],
      technologies: [
        'Honda Sensing driver assist technology',
        'HondaLink infotainment system',
        'Earth Dreams Technology engines',
      ],
    },
    {
      id: 5,
      make: 'Chevrolet',
      model: 'Camaro',
      year: 2020,
      price: 4000000,
      imageUrl: '/images/camaro.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'Chevrolet MyLink infotainment system',
        'OnStar connected car service',
        'EcoTec engines',
      ],
    },
    {
      id: 6,
      make: 'BMW',
      model: '3 Series',
      year: 2021,
      price: 450000,
      imageUrl: '/images/3series.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'iDrive infotainment system',
        'ConnectedDrive connected car services',
        'TwinPower Turbo engines',
      ],
    },
    {
      id: 7,
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2020,
      price: 500000,
      imageUrl: '/images/cclass.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'COMAND infotainment system',
        'Mercedes me connect services',
        '4MATIC all-wheel drive system',
      ],
    },
    {
      id: 8,
      make: 'Audi',
      model: 'A4',
      year: 2019,
      price: 350000,
      imageUrl: '/images/a4.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'MMI infotainment system',
        'Audi connect services',
        'quattro all-wheel drive system',
      ],
    },
    {
      id: 9,
      make: 'Subaru',
      model: 'Outback',
      year: 2018,
      price: 300000,
      imageUrl: '/images/outback.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'Uconnect infotainment system',
        'Jeep Wave owner loyalty program',
        'Trail Rated off-road capability',
      ],
    },
    {
      id: 10,
      make: 'Mazda',
      model: 'CX-5',
      year: 2021,
      price: 300000,
      imageUrl: '/images/cx5.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'NissanConnect infotainment system',
        'Nissan Safety Shield driver assist technology',
        'Xtronic CVT transmission',
      ],
    },
    {
      id: 11,
      make: 'Mazda',
      model: 'CX-5',
      year: 2021,
      price: 300000,
      imageUrl: '/images/cx5.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'NissanConnect infotainment system',
        'Nissan Safety Shield driver assist technology',
        'Xtronic CVT transmission',
      ],
    },
    {
      id: 12,
      make: 'Mazda',
      model: 'CX-5',
      year: 2021,
      price: 300000,
      imageUrl: '/images/cx5.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'NissanConnect infotainment system',
        'Nissan Safety Shield driver assist technology',
        'Xtronic CVT transmission',
      ],
    },
    {
      id: 13,
      make: 'Mazda',
      model: 'CX-5',
      year: 2021,
      price: 300000,
      imageUrl: '/images/cx5.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'NissanConnect infotainment system',
        'Nissan Safety Shield driver assist technology',
        'Xtronic CVT transmission',
      ],
    },
    {
      id: 14,
      make: 'Mazda',
      model: 'CX-5',
      year: 2021,
      price: 300000,
      imageUrl: '/images/cx5.jpg',
      engine: '2.5L 4-Cylinder DOHC 16V',
      transmission: 'CVT',
      fuelType: 'Gasoline',
      color: 'Blue',
      mileage: 50000,
      features: [
        'Air conditioning',
        'Bluetooth connectivity',
        'Rearview camera',
        'Satellite radio',
        'Sunroof',
        'Leather seats',
        'Navigation system',
        'Adaptive cruise control',
      ],
      technologies: [
        'NissanConnect infotainment system',
        'Nissan Safety Shield driver assist technology',
        'Xtronic CVT transmission',
      ],
    },
  ];
};
export default getCars;
