export default [
  'Otomatik şanzıman',
  'Manuel şanzıman',
  'Hidrolik direksiyon',
  'Elektrikli camlar',
  'Güç kilitleri',
  'Uzaktan Anahtarsız Giriş',
  'Basmalı düğme başlatma',
  'Seyir kontrolü',
  'Klima',
  'İklim kontrolü',
  'Isıtmalı koltuklar',
  'Deri koltuklar',
  'Elektrikli koltuklar',
  'Hafızalı koltuklar',
  'Sunroof',
  'Açılır tavan',
  'Eğimli direksiyon simidi',
  'Teleskopik direksiyon',
  'Dikiz kamera',
  'Yedek sensörler',
  'Navigasyon sistemi',
  'Bilgi-eğlence sistemi',
  'Bluetooth bağlantısı',
  'USB bağlantısı',
  'Wi-Fi bağlantısı',
  'Android oto',
  'Apple CarPlay',
  'Uydu radyo',
  'HD Radyo',
  'otomatik farlar',
  'Uyarlanabilir farlar',
  'LED farlar',
  'Sis farları',
  'Otomatik silecekler',
  'Yağmur algılayan silecekler',
  'Arka cam buğu çözücü',
  'Çift bölgeli klima kontrolü',
  'Üç bölgeli iklim kontrolü',
  'Anahtarsız giriş ve çalıştırma',
  'Kör nokta izleme',
  'Arka çapraz trafik uyarısı',
  'Şerit kalkış uyarısı',
  'Şeritte kalma yardımcısı',
  'Uyarlanabilir hız sabitleyici',
  'Otomatik acil frenleme',
  'Elektronik Denge Kontrolü',
  'Çekiş kontrolü',
  'ABS Fren sistemi',
  'Otomatik park etme',
  'Elektrikli direksiyon',
];
