// #searchCategoryContainer h2
import { ICarModels } from '../types';

const models: ICarModels = {
  Acura: { models: [] },
  Aion: { models: [] },
  'Alfa Romeo': { models: [] },
  Anadol: { models: [] },
  'Aston Martin': { models: [] },
  Audi: {
    models: [
      'A1',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'E-Tron GT',
      'R8',
      'RS',
      'S Serisi',
      'TT',
      'TTS',
      '80 Serisi',
      '90 Serisi',
      '100 Serisi',
      '200 Serisi',
      'Cabrio',
    ],
  },
  Bentley: { models: [] },
  BMW: {
    models: [
      '1 Serisi',
      '2 Serisi',
      '3 Serisi',
      '4 Serisi',
      '5 Serisi',
      '6 Serisi',
      '7 Serisi',
      '8 Serisi',
      'i Serisi',
      'M Serisi',
      'Z Serisi',
    ],
  },
  Bugatti: { models: [] },
  Buick: { models: [] },
  Cadillac: { models: [] },
  Chery: { models: [] },
  Chevrolet: {
    models: [
      'Aveo',
      'Camaro',
      'Caprice',
      'Celebrity',
      'Corvette',
      'Cruze',
      'Epica',
      'Evanda',
      'Impala',
      'Kalos',
      'Lacetti',
      'Monte Carlo',
      'Rezzo',
      'Spark',
    ],
  },
  Chrysler: { models: [] },
  Citroen: {
    models: [
      'AMI',
      'C-Elysee',
      'C1',
      'C2',
      'C3',
      'C3 Picasso',
      'C4',
      'C4 Grand Picasso',
      'C4 Picasso',
      'C5',
      'C6',
      'C8',
      'Saxo',
      'Xsara',
      'AX',
      'BX',
      'Evasion',
      'Xantia',
      'XM',
      'ZX',
    ],
  },
  Dacia: { models: ['Jogger', 'Lodgy', 'Logan', 'Sandero', 'Nova', 'Solenza'] },
  Daewoo: { models: [] },
  Daihatsu: { models: [] },
  Dodge: { models: [] },
  'DS Automobiles': { models: [] },
  Ferrari: { models: [] },
  Fiat: {
    models: [
      '124 Spider',
      'Albea',
      'Brava',
      'Bravo',
      '126 Bis',
      'Coupe',
      'Croma',
      '500 Ailesi',
      'Egea',
      'Idea',
      'Linea',
      'Marea',
      'Multipla',
      'Palio',
      'Panda',
      'Punto',
      'Regata',
      'Sedici',
      'Seicento',
      'Siena',
      'Stilo',
      'Tempra',
      'Tipo',
      'Ulysse',
      'UNO',
    ],
  },
  Fisker: { models: [] },
  Ford: {
    models: [
      'B-Max',
      'C-Max',
      'Escort',
      'Fiesta',
      'Focus',
      'Fusion',
      'Galaxy',
      'Grand C-Max',
      'Ka',
      'Mondeo',
      'Mustang',
      'S-Max',
      'Taurus',
      'Crown Victoria',
      'Festiva',
      'Granada',
      'Orion',
      'Probe',
      'Scorpio',
      'Sierra',
      'Taunus',
    ],
  },
  Geely: { models: [] },
  Honda: {
    models: [
      'Accord',
      'City',
      'Civic',
      'CR-Z',
      'CRX',
      'E',
      'Integra',
      'Jazz',
      'Legend',
      'Prelude',
      'S2000',
      'Shuttle',
      'Stream',
    ],
  },
  Hyundai: {
    models: [
      'Accent',
      'Accent Blue',
      'Accent Era',
      'Atos',
      'Coupe',
      'Elantra',
      'Equus',
      'Excel',
      'Genesis',
      'Getz',
      'Grandeur',
      'i10',
      'i20',
      'i20 Active',
      'i20 N',
      'i20 Troy',
      'i30',
      'i40',
      'Ioniq',
      'iX20',
      'Matrix',
      'S-Coupe',
      'Sonata',
      'Trajet',
    ],
  },
  Ikco: { models: [] },
  Infiniti: { models: [] },
  Isuzu: { models: [] },
  Jaguar: { models: [] },
  Kia: {
    models: [
      'Capital',
      'Carens',
      'Carnival',
      'Ceed',
      'Cerato',
      'Clarus',
      'Magentis',
      'Opirus',
      'Optima',
      'Picanto',
      'Pride',
      'Pro Ceed',
      'Rio',
      'Sephia',
      'Shuma',
      'Stinger',
      'Venga',
    ],
  },
  Lada: { models: [] },
  Lamborghini: { models: [] },
  Lancia: { models: [] },
  Leapmotor: { models: [] },
  Lexus: { models: [] },
  Lincoln: { models: [] },
  Lotus: { models: [] },
  Marcos: { models: [] },
  Maserati: { models: [] },
  Mazda: {
    models: [
      '2',
      '3',
      '5',
      '6',
      'MPV',
      'MX',
      'Premacy',
      '121',
      '323',
      '626',
      '929',
      'Lantis',
      'RX',
      'Xedos',
    ],
  },
  McLaren: { models: [] },
  'Mercedes - Benz': {
    models: [
      'A Serisi',
      'AMG GT',
      'B Serisi',
      'C Serisi',
      'CL',
      'CLA',
      'CLC',
      'CLK',
      'CLS',
      'E Serisi',
      'EQE',
      'EQS',
      'Maybach S',
      'R Serisi',
      'S Serisi',
      'SL',
      'SLC',
      'SLK',
      'SLS AMG',
      '190',
      '200',
      '220',
      '230',
      '240',
      '250',
      '260',
      '280',
      '300',
      '320',
      '380',
      '420',
      '500',
      '560',
      '600',
    ],
  },
  Mercury: { models: [] },
  MG: { models: [] },
  Mini: {
    models: [
      'Cooper',
      'Cooper Clubman',
      'Cooper Electric',
      'John Cooper',
      'One',
      'Cooper S',
    ],
  },
  Mitsubishi: {
    models: [
      'Attrage',
      'Colt',
      'Galant',
      'Lancer',
      'Lancer Evolution',
      'Carisma',
      'Chariot',
      'Eclipse',
      'Grandis',
      'Space Star',
      'Space Wagon',
    ],
  },
  Moskwitsch: { models: [] },
  Nissan: {
    models: [
      '200 SX',
      '350 Z',
      'Almera',
      'Altima',
      'Bluebird',
      'Cedric',
      'GT-R',
      'Laurel Altima',
      'Maxima',
      'Micra',
      'Note',
      'NX Coupe',
      'Primera',
      'Pulsar',
      'Sunny',
      'Teana',
      'Tino',
    ],
  },
  Opel: {
    models: [
      'Adam',
      'Agila',
      'Ampera',
      'Ascona',
      'Astra',
      'Calibra',
      'Cascada',
      'Corsa',
      'GT (Roadster)',
      'Insignia',
      'Kadett',
      'Manta',
      'Meriva',
      'Omega',
      'Rekord',
      'Senator',
      'Signum',
      'Tigra',
      'Vectra',
      'Zafira',
    ],
  },
  Peugeot: {
    models: [
      '106',
      '107',
      '205',
      '206',
      '206 +',
      '207',
      '208',
      '301',
      '305',
      '306',
      '307',
      '308',
      '405',
      '406',
      '407',
      '508',
      '605',
      '607',
      '806',
      '807',
      'RCZ',
    ],
  },
  Plymouth: { models: [] },
  Polestar: { models: [] },
  Pontiac: { models: [] },
  Porsche: {
    models: ['718', '911', '928', 'Boxster', 'Cayman', 'Panamera', 'Taycan'],
  },
  Proton: { models: [] },
  Renault: {
    models: [
      'Clio',
      'Espace',
      'Fluence',
      'Fluence Z.E.',
      'Grand Espace',
      'Grand Scenic',
      'Laguna',
      'Latitude',
      'Megane',
      'Modus',
      'Safrane',
      'Scenic',
      'Symbol',
      'Taliant',
      'Talisman',
      'Twingo',
      'Twizy',
      'Vel Satis',
      'ZOE',
      'R 5',
      'R 9',
      'R 11',
      'R 12',
      'R 19',
      'R 21',
      'R 25',
    ],
  },
  RKS: { models: [] },
  'Rolls-Royce': { models: [] },
  Rover: {
    models: [
      '25',
      '45',
      '75',
      '200',
      '214',
      '216',
      '220',
      '400',
      '414',
      '416',
      '420',
      '620',
      '820',
      '827',
      'Streetwise',
    ],
  },
  Saab: { models: [] },
  Saturn: { models: [] },
  Seat: {
    models: [
      'Alhambra',
      'Altea',
      'Arosa',
      'Cordoba',
      'Exeo',
      'Ibiza',
      'Leon',
      'Marbella',
      'Toledo',
    ],
  },
  Skoda: {
    models: [
      'Citigo',
      'Fabia',
      'Favorit',
      'Felicia',
      'Forman',
      'Octavia',
      'Rapid',
      'Roomster',
      'Scala',
      'Superb',
    ],
  },
  Smart: { models: [] },
  Subaru: {
    models: ['BRZ', 'Impreza', 'Legacy', 'Levorg', 'Justy', 'SVX', 'Vivio'],
  },
  Suzuki: {
    models: [
      'Alto',
      'Baleno',
      'Reno',
      'Splash',
      'Swift',
      'SX4',
      'Liana',
      'Maruti',
    ],
  },
  Tata: { models: [] },
  Tesla: { models: ['Model 3', 'Model S', 'Model X', 'Model Y'] },
  Tofaş: { models: ['Doğan', 'Kartal', 'Murat', 'Şahin', 'Serçe'] },
  Toyota: {
    models: [
      'Auris',
      'Avensis',
      'Camry',
      'Carina',
      'Celica',
      'Corolla',
      'Corona',
      'Cressida',
      'GT86',
      'MR2',
      'Paseo',
      'Picnic',
      'Previa',
      'Prius',
      'Starlet',
      'Supra',
      'Urban Cruiser',
      'Verso',
      'Windom',
      'Yaris',
    ],
  },
  Volkswagen: {
    models: [
      'Arteon',
      'Beetle',
      'Bora',
      'EOS',
      'FOX',
      'Golf',
      'ID.3',
      'Jetta',
      'Lupo',
      'Passat',
      'Passat Alltrack',
      'Passat Variant',
      'Phaeton',
      'Polo',
      'Scirocco',
      'Sharan',
      'Touran',
      'Up Club',
      'VW CC',
      'Vento',
    ],
  },
  Volvo: {
    models: [
      'C30',
      'C70',
      'S40',
      'S60',
      'S70',
      'S80',
      'S90',
      'V40',
      'V40 Cross Country',
      'V50',
      'V60',
      'V60 Cross Country',
      'V70',
      'V90 Cross Country',
      '440',
      '460',
      '740',
      '850',
      '940',
      '960',
    ],
  },
  XEV: { models: [] },
  Yuki: { models: [] },
};

export default models;
