const technologies = [
  'Kilitlenme önleyici fren sistemleri (ABS)',
  'Otomatik acil frenleme (AEB)',
  'Uyarlanabilir hız sabitleyici (ACC)',
  'Şeritten ayrılma uyarısı (LDW)',
  'Şeritte kalma yardımcısı (LKA)',
  'Kör nokta tespiti (BSD)',
  'Arka görüş kameraları',
  'Otomatik park etme',
  'Uyarlanabilir farlar',
  'Gece görüş sistemleri',
  'Otomatik uzun farlar',
  'Head-up ekranları (HUD)',
  'Kablosuz (OTA) güncellemeler',
  'Elektrikli hidrolik direksiyon (EPS)',
  'Elektrikli aktarma organları',
  'Hibrit aktarma organları',
  'Plug-in hibrit aktarma organları',
  'Yakıt hücreli aktarma organları',
  'Pil yönetim sistemleri',
  'Rejeneratif frenleme',
  'Süperşarjlar ve turboşarjlar',
  'Değişken supap zamanlaması',
  'Direkt yakıt enjeksiyonu',
  'Gelişmiş sürücü destek sistemleri (ADAS)',
  'Otonom sürüş teknolojisi',
];
export default technologies;
